call_parentheses = "Always"
collapse_simple_statement = "Never"
column_width = 79
indent_type = "Spaces"
indent_width = 2
line_endings = "Unix"
quote_style = "AutoPreferSingle"
remove_trailing_separators = false
